charon {
    load_modular = no
    plugins {
        openssl {
        }
        nonce {
        }
        random {
        }
        socket-default {
            use_broadcast = yes
        }
        kernel-netlink {
        }
        kernel-pfroute {
        }
        kernel-pfkey {
        }
        resolve {
        }
        stroke {
            socket = unix:///var/run/ipsec-ns-west/charon.ctl
        }
        vici {
        }
        xauth-pam {
        }
        eap-identity {
        }
        eap-mschapv2 {
        }
        eap-tls {
        }
        eap-ttls {
        }
        eap-peap {
        }
        xcbc {
        }
        hmac {
        }
        aes {
        }
        sha2 {
        }
        sha1 {
        }
        gcm {
        }
        ccm {
        }
        ctr {
        }
        cmac {
        }
        pbkdf2 {
        }
        fips-prf {
        }
        md5 {
        }
        pkcs1 {
        }
        pkcs8 {
        }
        pkcs12 {
        }
        pem {
        }
        x509 {
        }
        pubkey {
        }
        sshkey {
        }
        revocation {
        }
        constraints {
        }
        acert {
        }
        save-keys {
        }
    }
    pidfile = /var/run/ipsec-ns-west/charon.pid
}
